# Generated by Django 5.1.4 on 2024-12-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0002_alter_to_do_list_description_alter_to_do_list_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='status',
            field=models.CharField(choices=[('Не выполнено', 'Не выполнено'), ('Выполнено', 'Выполнено')], default='Не выполнено', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='term',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок'),
        ),
    ]
