# Generated by Django 5.1.4 on 2024-12-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0003_alter_to_do_list_status_alter_to_do_list_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='to_do_list',
            name='term',
            field=models.DateTimeField(blank=True, default='Без срока', null=True, verbose_name='Срок'),
        ),
    ]
