# Generated by Django 5.1.4 on 2024-12-19 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_app', '0004_alter_to_do_list_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AlterField(
            model_name='to_do_list',
            name='term',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок'),
        ),
        migrations.CreateModel(
            name='To_do_listTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_list', to='to_do_list_app.tags', verbose_name='Тег')),
                ('to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_do_list', to='to_do_list_app.to_do_list', verbose_name='Список дел')),
            ],
            options={
                'verbose_name': 'Связь',
                'verbose_name_plural': 'Связи',
            },
        ),
        migrations.AddField(
            model_name='tags',
            name='tags',
            field=models.ManyToManyField(related_name='tag', through='to_do_list_app.To_do_listTags', to='to_do_list_app.to_do_list', verbose_name='Тег'),
        ),
    ]
